### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dimiandre** [CosmosContracts/old-website#2]
- [x] Rename to "Milestones"
- [x] Show "Read more" or "Emeris" instead of plain text URLs
- [x] Set launch date to October 1st
